<a href="https://colab.research.google.com/github/lokeshchandr/Python_assingment2/blob/main/iiti_assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:

mylist = list('abcdefghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

series_from_list = pd.Series(mylist)
print("Series from list:")
print(series_from_list)


series_from_array = pd.Series(myarr)
print("\nSeries from NumPy array:")
print(series_from_array)


series_from_dict = pd.Series(mydict)
print("\nSeries from dictionary:")
print(series_from_dict)


Series from list:
0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

Series from NumPy array:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64

Series from dictionary:
a     0
b     1
c     2
d     3
e     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [ ]:
import pandas as pd
import numpy as np

mylist = list('abcdefghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df = ser.reset_index()


df.columns = ['letter', 'value']


print(df)


   letter  value
0       a      0
1       b      1
2       c      2
3       d      3
4       e      4
5       f      5
6       g      6
7       h      7
8       i      8
9       j      9
10      k     10
11      l     11
12      m     12
13      n     13
14      o     14
15      p     15
16      q     16
17      r     17
18      s     18
19      t     19
20      u     20
21      v     21
22      w     22
23      x     23
24      y     24
25      z     25


In [ ]:

import pandas as pd


ser = pd.Series(np.random.normal(10, 5, 25))


minimum = ser.min()
percentile_25 = ser.quantile(0.25)
median = ser.median()
percentile_75 = ser.quantile(0.75)
maximum = ser.max()


print("Minimum:", minimum)
print("25th Percentile:", percentile_25)
print("Median:", median)
print("75th Percentile:", percentile_75)
print("Maximum:", maximum)


Minimum: 4.408408768722819
25th Percentile: 7.809321886477913
Median: 11.105898346107002
75th Percentile: 14.084235358428895
Maximum: 18.0949083033763


In [ ]:
import pandas as pd
import numpy as np

ser1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))


df = pd.concat([ser1, ser2], axis=1)


df.columns = ['letter', 'number']


print(df)


   letter  number
0       a       0
1       b       1
2       c       2
3       d       3
4       e       4
5       f       5
6       g       6
7       h       7
8       i       8
9       j       9
10      k      10
11      l      11
12      m      12
13      n      13
14      o      14
15      p      15
16      q      16
17      r      17
18      s      18
19      t      19
20      u      20
21      v      21
22      w      22
23      x      23
24      y      24
25      z      25


In [ ]:
import pandas as pd

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

filtered_ser1 = ser1[~ser1.isin(ser2)]

print(filtered_ser1)


0    1
1    2
2    3
dtype: int64


In [ ]:
import pandas as pd

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1_not_in_ser2 = ser1[~ser1.isin(ser2)]


ser2_not_in_ser1 = ser2[~ser2.isin(ser1)]

result = ser1_not_in_ser2.append(ser2_not_in_ser1)


print(result)


0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


<ipython-input-7-d612cdd20599>:11: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = ser1_not_in_ser2.append(ser2_not_in_ser1)


In [ ]:
import pandas as pd


ser = pd.Series(np.random.normal(10, 5, 25))

minimum = ser.min()
percentile_25 = ser.quantile(0.25)
median = ser.median()
percentile_75 = ser.quantile(0.75)
maximum = ser.max()

print("Minimum:", minimum)
print("25th Percentile:", percentile_25)
print("Median:", median)
print("75th Percentile:", percentile_75)
print("Maximum:", maximum)


Minimum: 2.8389904254136926
25th Percentile: 7.487512289598497
Median: 9.448579899814069
75th Percentile: 12.369036589049704
Maximum: 19.71795526479703


In [ ]:
import pandas as pd
import numpy as np

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

#t0  Calculate the frequency counts of each unique value
frequency_counts = ser.value_counts()


print(frequency_counts)


d    7
g    5
e    5
h    4
f    3
a    2
b    2
c    2
dtype: int64


In [ ]:
import pandas as pd
import numpy as np

np.random.seed(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

# Calculate the frequency counts of each unique value
value_counts = ser.value_counts()

# Get the top 2 most frequent items
top_frequent = value_counts.index[:2]

# Replace everything else as 'Other'
ser_replaced = ser.apply(lambda x: x if x in top_frequent else 'Other')

# Display the result
print(ser_replaced)


0         1
1         1
2         4
3         4
4         4
5         4
6         1
7     Other
8     Other
9         1
10    Other
11    Other
dtype: object


### **numpy**

In [ ]:
# To get the common items between two Python NumPy arrays a and b,
# we use the intersect1d() function from NumPy.
# This function returns the sorted, unique values that are in both arrays.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Get the common items between the two arrays
common_items = np.intersect1d(a, b)

print(common_items)

[2 4]


to remove from one NumPy array a those items that exist in another array b, we use the setdiff1d() function from NumPy. This function returns the sorted, unique values that are in array a but not in array b.

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# Remove items from a that exist in b
result = np.setdiff1d(a, b)


print(result)


[1 2 3 4]


In [ ]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])

#all items between 5 and 10 from array a
result = a[(a >= 5) & (a <= 10)]

print(result)


[ 6  9 10]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])


pos = np.where(a == b)[0]
print(pos)


[1 3 5 7]


In [ ]:
import numpy as np

arr = np.arange(9).reshape(3, 3)


reversed_arr = arr[::-1]


print(reversed_arr)


[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [ ]:
import numpy as np

iris_data = np.genfromtxt('Iris.csv', delimiter=',', skip_header=1, usecols=[1])

mean_sepallength = np.mean(iris_data)
median_sepallength = np.median(iris_data)
std_sepallength = np.std(iris_data)


print("Mean Sepal Length:", mean_sepallength)
print("Median Sepal Length:", median_sepallength)
print("Standard Deviation of Sepal Length:", std_sepallength)



Mean Sepal Length: 5.843333333333334
Median Sepal Length: 5.8
Standard Deviation of Sepal Length: 0.8253012917851409


In [ ]:

iris_data = np.genfromtxt('Iris.csv', delimiter=',', skip_header=1, usecols=[1])
min_sepallength = np.min(iris_data)
max_sepallength = np.max(iris_data)

normalized_sepallength = (iris_data - min_sepallength) / (max_sepallength - min_sepallength)

print(normalized_sepallength)


[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [ ]:
import numpy as np

# Load data from 'winequality-red.csv'
wine_quality = np.genfromtxt('winequality-red.csv', delimiter=',', dtype='float', usecols=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], skip_header=1)

wine_quality[np.isnan(wine_quality)] = 0
print(wine_quality)


FileNotFoundError: ignored

In [ ]:
import numpy as np

# Loading data from 'mushrooms.csv'
mushroom = np.genfromtxt('mushrooms.csv', delimiter=',', dtype=object, usecols=[0], skip_header=1)

unique_values, counts = np.unique(mushroom, return_counts=True)
for value, count in zip(unique_values, counts):
    print(f"{value}: {count}")


b'e': 4208
b'p': 3916


In [ ]:
import numpy as np

# Loading data from 'diabetes.csv'
diabetes_data = np.genfromtxt('diabetes.csv', delimiter=',', dtype='float', usecols=[0, 1, 2, 3, 4, 5, 6, 7], skip_header=1)

# Checking for NaN values in each row
row_mask = ~np.isnan(diabetes_data).any(axis=1)

# Selecting  rows that do not have any NaN value
rows_without_nan = diabetes_data[row_mask]
print(rows_without_nan)


[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
